services:
  database:
    image: postgres:15-alpine
    container_name: sosyaliskanlik-db
    environment:
      POSTGRES_DB: HabitTrackerDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis: # <-- BU SERVİSİN BURADA OLDUĞUNDAN EMİN OL
    image: redis:7-alpine
    container_name: sosyaliskanlik-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data

  backend:
    container_name: sosyaliskanlik-backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5282:8080"
    environment:
      - ConnectionStrings__Redis=redis:6379
      - ConnectionStrings__DefaultConnection=Host=database;Port=5432;Database=HabitTrackerDb;Username=postgres;Password=${POSTGRES_PASSWORD}
      - JwtSettings__Secret=${JWT_SECRET}
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      - database
      - redis

  frontend:
    container_name: sosyaliskanlik-frontend
    build:
      context: ./client
      dockerfile: Dockerfile.frontend
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:5282
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  redis_data: 
    driver: local

